"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-14

Hand-written (not autogenerated) -- no live Postgres instance was available in
the environment that authored this migration, so it was written directly from
app/models/*.py instead of `alembic revision --autogenerate`. Verify it against
a real database with `alembic upgrade head` before relying on it.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_pk():
    return sa.Column(
        "id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")
    )


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    op.create_table(
        "users",
        _uuid_pk(),
        sa.Column("email", sa.String, nullable=False, unique=True),
        sa.Column("hashed_password", sa.String, nullable=False),
        sa.Column("full_name", sa.String, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "instruments",
        _uuid_pk(),
        sa.Column("symbol", sa.String, nullable=False, unique=True),
        sa.Column("exchange", sa.String, nullable=False, server_default="NSE"),
        sa.Column("isin", sa.String, nullable=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("sector", sa.String, nullable=True),
        sa.Column("instrument_key", sa.String, nullable=True),
        sa.Column("lot_size", sa.Integer, nullable=False, server_default="1"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_instruments_symbol", "instruments", ["symbol"])

    op.create_table(
        "news",
        _uuid_pk(),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("title", sa.String, nullable=False),
        sa.Column("url", sa.String, nullable=False, unique=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_summary", sa.String, nullable=True),
        sa.Column("companies", postgresql.JSON, nullable=False, server_default="[]"),
        sa.Column("sectors", postgresql.JSON, nullable=False, server_default="[]"),
    )

    op.create_table(
        "model_versions",
        _uuid_pk(),
        sa.Column("model_name", sa.String, nullable=False),
        sa.Column("version", sa.String, nullable=False),
        sa.Column("parameters", postgresql.JSON, nullable=False, server_default="{}"),
        sa.Column("prompt_version", sa.String, nullable=True),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "data_sources",
        _uuid_pk(),
        sa.Column("name", sa.String, nullable=False, unique=True),
        sa.Column("kind", sa.String, nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="unconfigured"),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", postgresql.JSON, nullable=False, server_default="{}"),
    )

    op.create_table(
        "council_runs",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("market_regime", sa.String, nullable=False),
        sa.Column("universe_size", sa.Integer, nullable=False),
        sa.Column("candidates_after_screen", sa.Integer, nullable=False),
        sa.Column("candidates_after_kronos_news", sa.Integer, nullable=False),
        sa.Column("candidates_to_council", sa.Integer, nullable=False),
        sa.Column("plan", postgresql.JSON, nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="running"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "recommendation_jobs",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="queued"),
        sa.Column("error", sa.String, nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result_council_run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("council_runs.id"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "user_profiles",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("age", sa.Integer, nullable=False),
        sa.Column("employment_status", sa.String, nullable=False),
        sa.Column("monthly_income_range", sa.String, nullable=False),
        sa.Column("monthly_investable_amount", sa.Float, nullable=False),
        sa.Column("total_initial_investment", sa.Float, nullable=False),
        sa.Column("existing_investments", postgresql.JSON, nullable=False, server_default="{}"),
        sa.Column("existing_debt", sa.Float, nullable=False, server_default="0"),
        sa.Column("emergency_fund_status", sa.String, nullable=False),
        sa.Column("dependents", sa.Integer, nullable=False, server_default="0"),
        sa.Column("investment_objective", sa.String, nullable=False),
        sa.Column("investment_horizon_years", sa.Integer, nullable=False),
        sa.Column("liquidity_requirement", sa.String, nullable=False),
        sa.Column("investment_frequency", sa.String, nullable=False),
        sa.Column("raw_risk_answers", postgresql.JSON, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "risk_profiles",
        _uuid_pk(),
        sa.Column(
            "user_profile_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("user_profiles.id"), nullable=False
        ),
        sa.Column("risk_score", sa.Integer, nullable=False),
        sa.Column("risk_profile", sa.String, nullable=False),
        sa.Column("investment_horizon_years", sa.Integer, nullable=False),
        sa.Column("capital", sa.Float, nullable=False),
        sa.Column("monthly_contribution", sa.Float, nullable=False),
        sa.Column("objective", sa.String, nullable=False),
        sa.Column("liquidity_requirement", sa.String, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "market_prices",
        _uuid_pk(),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=False
        ),
        sa.Column("price", sa.Float, nullable=False),
        sa.Column("open", sa.Float, nullable=False),
        sa.Column("high", sa.Float, nullable=False),
        sa.Column("low", sa.Float, nullable=False),
        sa.Column("close", sa.Float, nullable=False),
        sa.Column("volume", sa.Integer, nullable=False),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("is_stale", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("market_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "market_candles",
        _uuid_pk(),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=False
        ),
        sa.Column("interval", sa.String, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float, nullable=False),
        sa.Column("high", sa.Float, nullable=False),
        sa.Column("low", sa.Float, nullable=False),
        sa.Column("close", sa.Float, nullable=False),
        sa.Column("volume", sa.Integer, nullable=False),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_market_candles_instrument_interval_ts",
        "market_candles",
        ["instrument_id", "interval", "timestamp"],
    )

    op.create_table(
        "fundamental_metrics",
        _uuid_pk(),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=False
        ),
        sa.Column("as_of_date", sa.Date, nullable=False),
        sa.Column("revenue", sa.Float, nullable=True),
        sa.Column("revenue_growth", sa.Float, nullable=True),
        sa.Column("ebitda", sa.Float, nullable=True),
        sa.Column("ebitda_margin", sa.Float, nullable=True),
        sa.Column("ebit", sa.Float, nullable=True),
        sa.Column("pat", sa.Float, nullable=True),
        sa.Column("eps", sa.Float, nullable=True),
        sa.Column("eps_growth", sa.Float, nullable=True),
        sa.Column("operating_cash_flow", sa.Float, nullable=True),
        sa.Column("free_cash_flow", sa.Float, nullable=True),
        sa.Column("total_debt", sa.Float, nullable=True),
        sa.Column("debt_to_equity", sa.Float, nullable=True),
        sa.Column("interest_coverage", sa.Float, nullable=True),
        sa.Column("roe", sa.Float, nullable=True),
        sa.Column("roce", sa.Float, nullable=True),
        sa.Column("operating_margin", sa.Float, nullable=True),
        sa.Column("net_margin", sa.Float, nullable=True),
        sa.Column("pe", sa.Float, nullable=True),
        sa.Column("forward_pe", sa.Float, nullable=True),
        sa.Column("pb", sa.Float, nullable=True),
        sa.Column("ev_ebitda", sa.Float, nullable=True),
        sa.Column("dividend_yield", sa.Float, nullable=True),
        sa.Column("promoter_holding", sa.Float, nullable=True),
        sa.Column("promoter_pledging", sa.Float, nullable=True),
        sa.Column("institutional_ownership", sa.Float, nullable=True),
        sa.Column("market_cap", sa.Float, nullable=True),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "technical_features",
        _uuid_pk(),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=False
        ),
        sa.Column("timeframe", sa.String, nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sma_20", sa.Float, nullable=True),
        sa.Column("sma_50", sa.Float, nullable=True),
        sa.Column("sma_200", sa.Float, nullable=True),
        sa.Column("ema_12", sa.Float, nullable=True),
        sa.Column("ema_26", sa.Float, nullable=True),
        sa.Column("rsi_14", sa.Float, nullable=True),
        sa.Column("macd", sa.Float, nullable=True),
        sa.Column("macd_signal", sa.Float, nullable=True),
        sa.Column("macd_hist", sa.Float, nullable=True),
        sa.Column("bb_upper", sa.Float, nullable=True),
        sa.Column("bb_lower", sa.Float, nullable=True),
        sa.Column("atr_14", sa.Float, nullable=True),
        sa.Column("adx_14", sa.Float, nullable=True),
        sa.Column("volatility_30d", sa.Float, nullable=True),
        sa.Column("drawdown_1y", sa.Float, nullable=True),
        sa.Column("beta", sa.Float, nullable=True),
        sa.Column("trend", sa.String, nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "kronos_predictions",
        _uuid_pk(),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=False
        ),
        sa.Column("forecast_horizon", sa.String, nullable=False),
        sa.Column("direction", sa.String, nullable=False),
        sa.Column("predicted_return", sa.Float, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("input_timeframe", sa.String, nullable=False),
        sa.Column("model_name", sa.String, nullable=False, server_default="Kronos"),
        sa.Column("model_version", sa.String, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "finbert_analysis",
        _uuid_pk(),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=False
        ),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sentiment_score", sa.Float, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("article_count", sa.Integer, nullable=False),
        sa.Column("model_name", sa.String, nullable=False, server_default="FinBERT"),
        sa.Column("model_version", sa.String, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "news_analysis",
        _uuid_pk(),
        sa.Column("news_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("news.id"), nullable=False),
        sa.Column("event_type", sa.String, nullable=False),
        sa.Column("sentiment", sa.Float, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("relevance", sa.Float, nullable=False),
        sa.Column("importance", sa.Float, nullable=False),
        sa.Column("model_name", sa.String, nullable=False),
        sa.Column("model_version", sa.String, nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "portfolio_results",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("method", sa.String, nullable=False),
        sa.Column("candidate_symbols", postgresql.JSON, nullable=False),
        sa.Column("allocations", postgresql.JSON, nullable=False),
        sa.Column("expected_return", sa.Float, nullable=True),
        sa.Column("expected_volatility", sa.Float, nullable=True),
        sa.Column("sharpe", sa.Float, nullable=True),
        sa.Column("model_version", sa.String, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "candidate_scores",
        _uuid_pk(),
        sa.Column(
            "council_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("council_runs.id"), nullable=False
        ),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=False
        ),
        sa.Column("fundamental_score", sa.Float, nullable=True),
        sa.Column("technical_score", sa.Float, nullable=True),
        sa.Column("kronos_score", sa.Float, nullable=True),
        sa.Column("news_score", sa.Float, nullable=True),
        sa.Column("portfolio_score", sa.Float, nullable=True),
        sa.Column("risk_score", sa.Float, nullable=True),
        sa.Column("final_score", sa.Float, nullable=False),
        sa.Column("model_agreement", sa.Float, nullable=False),
        sa.Column("data_quality", sa.Float, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
    )

    op.create_table(
        "council_outputs",
        _uuid_pk(),
        sa.Column(
            "council_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("council_runs.id"), nullable=False
        ),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=True
        ),
        sa.Column("role", sa.String, nullable=False),
        sa.Column("content", postgresql.JSON, nullable=False),
        sa.Column("model_name", sa.String, nullable=False),
        sa.Column("model_version", sa.String, nullable=False),
        sa.Column("prompt_version", sa.String, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "recommendations",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column(
            "council_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("council_runs.id"), nullable=False
        ),
        sa.Column(
            "instrument_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("instruments.id"), nullable=False
        ),
        sa.Column("recommendation", sa.String, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("score", sa.Float, nullable=False),
        sa.Column("risk_level", sa.String, nullable=False),
        sa.Column("suggested_horizon", sa.String, nullable=False),
        sa.Column("strengths", postgresql.JSON, nullable=False),
        sa.Column("risks", postgresql.JSON, nullable=False),
        sa.Column("evidence", postgresql.JSON, nullable=False),
        sa.Column("rationale", sa.String, nullable=False),
        sa.Column("model_agreement", sa.Float, nullable=False),
        sa.Column("data_quality", sa.Float, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "portfolio_recommendations",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column(
            "council_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("council_runs.id"), nullable=False
        ),
        sa.Column(
            "portfolio_result_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("portfolio_results.id"),
            nullable=False,
        ),
        sa.Column("allocations", postgresql.JSON, nullable=False),
        sa.Column("notes", postgresql.JSON, nullable=False, server_default="[]"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "audit_logs",
        _uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("action", sa.String, nullable=False),
        sa.Column("entity_type", sa.String, nullable=False),
        sa.Column("entity_id", sa.String, nullable=True),
        sa.Column("meta", postgresql.JSON, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    for table in [
        "audit_logs",
        "portfolio_recommendations",
        "recommendations",
        "council_outputs",
        "candidate_scores",
        "portfolio_results",
        "news_analysis",
        "finbert_analysis",
        "kronos_predictions",
        "technical_features",
        "fundamental_metrics",
        "market_candles",
        "market_prices",
        "risk_profiles",
        "user_profiles",
        "recommendation_jobs",
        "council_runs",
        "data_sources",
        "model_versions",
        "news",
        "instruments",
        "users",
    ]:
        op.drop_table(table)
