"""add recommendation risk_tier and per-signal score columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-18

Hand-written (not autogenerated), matching 0001's approach -- no live Postgres
instance was available in the environment that authored this migration.
Verify it against a real database with `alembic upgrade head` before relying
on it. Adds columns backing app/scoring/subscores.py::risk_tier and the raw
per-signal ScoreBreakdown fields, all nullable so existing rows remain valid.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("recommendations", sa.Column("risk_tier", sa.String(), nullable=True))
    op.add_column("recommendations", sa.Column("fundamental_score", sa.Float(), nullable=True))
    op.add_column("recommendations", sa.Column("technical_score", sa.Float(), nullable=True))
    op.add_column("recommendations", sa.Column("kronos_score", sa.Float(), nullable=True))
    op.add_column("recommendations", sa.Column("news_score", sa.Float(), nullable=True))
    op.add_column("recommendations", sa.Column("portfolio_score", sa.Float(), nullable=True))
    op.add_column("recommendations", sa.Column("risk_score", sa.Float(), nullable=True))


def downgrade() -> None:
    op.drop_column("recommendations", "risk_score")
    op.drop_column("recommendations", "portfolio_score")
    op.drop_column("recommendations", "news_score")
    op.drop_column("recommendations", "kronos_score")
    op.drop_column("recommendations", "technical_score")
    op.drop_column("recommendations", "fundamental_score")
    op.drop_column("recommendations", "risk_tier")
