"""add recommendation_jobs progress tracking columns

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-23

Hand-written (not autogenerated), matching 0001/0002's approach. Backs
app/pipelines/progress.py::JobProgressTracker -- stage/progress_pct/stage_detail
are written through a separate session mid-pipeline-run so the job-status
poller sees live progress instead of only a final queued->running->done flip.
All nullable so existing rows remain valid.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("recommendation_jobs", sa.Column("stage", sa.String(), nullable=True))
    op.add_column("recommendation_jobs", sa.Column("progress_pct", sa.Float(), nullable=True))
    op.add_column("recommendation_jobs", sa.Column("stage_detail", sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_column("recommendation_jobs", "stage_detail")
    op.drop_column("recommendation_jobs", "progress_pct")
    op.drop_column("recommendation_jobs", "stage")
