"""add confidence_band and numeric risk_tier_score/breakdown

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-23

Hand-written (not autogenerated), matching prior migrations' approach. Both
values are already computed in app/scoring/final_score.py::compute_final_score
(confidence_band) and app/scoring/subscores.py::risk_tier_score_with_breakdown
(risk_tier_score / risk_tier_breakdown) but were previously discarded before
reaching persistence. All nullable so existing rows remain valid.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("recommendations", sa.Column("confidence_band", sa.String(), nullable=True))
    op.add_column("recommendations", sa.Column("risk_tier_score", sa.Float(), nullable=True))
    op.add_column("recommendations", sa.Column("risk_tier_breakdown", sa.JSON(), nullable=True))
    op.add_column("candidate_scores", sa.Column("confidence_band", sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column("candidate_scores", "confidence_band")
    op.drop_column("recommendations", "risk_tier_breakdown")
    op.drop_column("recommendations", "risk_tier_score")
    op.drop_column("recommendations", "confidence_band")
