"""Nifty50 seed universe (Section 15).

Loaded from `data/processed/nifty50_instruments.json`, generated by
`scripts/sync_instruments.py` against two live, official sources:
NSE's own Nifty50 constituent list and Upstox's instrument master. Re-run
that script periodically -- NSE rebalances Nifty50 semi-annually (Jan 31 /
Jul 31 cutoffs).

If that file hasn't been generated yet (fresh clone, sync not run), falls
back to a small hand-picked subset -- kept deliberately small rather than
guessing ISINs, per the "never invent data" hard rule (Section 43). Three of
this fallback's originally-hand-typed ISINs (KOTAKBANK, BAJFINANCE,
NESTLEIND) were caught wrong by cross-checking against the official NSE list
during development -- a real demonstration of why this shouldn't be
hand-maintained; run the sync script instead of trusting this fallback.
"""

import json
from dataclasses import dataclass

from app.core.config import DATA_DIR

INSTRUMENTS_JSON_PATH = DATA_DIR / "processed" / "nifty50_instruments.json"


@dataclass(frozen=True)
class SeedInstrument:
    symbol: str
    name: str
    isin: str
    sector: str
    instrument_key: str

    @property
    def yfinance_ticker(self) -> str:
        return f"{self.symbol}.NS"


_FALLBACK_SEED: list[SeedInstrument] = [
    SeedInstrument("RELIANCE", "Reliance Industries", "INE002A01018", "Energy", "NSE_EQ|INE002A01018"),
    SeedInstrument("TCS", "Tata Consultancy Services", "INE467B01029", "IT", "NSE_EQ|INE467B01029"),
    SeedInstrument("HDFCBANK", "HDFC Bank", "INE040A01034", "Financials", "NSE_EQ|INE040A01034"),
    SeedInstrument("ICICIBANK", "ICICI Bank", "INE090A01021", "Financials", "NSE_EQ|INE090A01021"),
    SeedInstrument("INFY", "Infosys", "INE009A01021", "IT", "NSE_EQ|INE009A01021"),
    SeedInstrument("HINDUNILVR", "Hindustan Unilever", "INE030A01027", "FMCG", "NSE_EQ|INE030A01027"),
    SeedInstrument("ITC", "ITC Limited", "INE154A01025", "FMCG", "NSE_EQ|INE154A01025"),
    SeedInstrument("SBIN", "State Bank of India", "INE062A01020", "Financials", "NSE_EQ|INE062A01020"),
    SeedInstrument("BHARTIARTL", "Bharti Airtel", "INE397D01024", "Telecom", "NSE_EQ|INE397D01024"),
    SeedInstrument("LT", "Larsen & Toubro", "INE018A01030", "Industrials", "NSE_EQ|INE018A01030"),
    SeedInstrument("AXISBANK", "Axis Bank", "INE238A01034", "Financials", "NSE_EQ|INE238A01034"),
    SeedInstrument("ASIANPAINT", "Asian Paints", "INE021A01026", "Consumer Durables", "NSE_EQ|INE021A01026"),
    SeedInstrument("MARUTI", "Maruti Suzuki", "INE585B01010", "Automobile", "NSE_EQ|INE585B01010"),
    SeedInstrument("SUNPHARMA", "Sun Pharmaceutical", "INE044A01036", "Pharma", "NSE_EQ|INE044A01036"),
    SeedInstrument("TITAN", "Titan Company", "INE280A01028", "Consumer Durables", "NSE_EQ|INE280A01028"),
    SeedInstrument("ULTRACEMCO", "UltraTech Cement", "INE481G01011", "Cement", "NSE_EQ|INE481G01011"),
    SeedInstrument("WIPRO", "Wipro", "INE075A01022", "IT", "NSE_EQ|INE075A01022"),
]


def _load_seed() -> list[SeedInstrument]:
    if not INSTRUMENTS_JSON_PATH.exists():
        return _FALLBACK_SEED
    data = json.loads(INSTRUMENTS_JSON_PATH.read_text())
    return [SeedInstrument(**row) for row in data["instruments"]]


NIFTY50_SEED: list[SeedInstrument] = _load_seed()
